[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "cd frontend && rm -f package-lock.json",
  "cd frontend && npm install --legacy-peer-deps"
]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "npx serve frontend/dist -l $PORT"
